lzy_doctrine:
    resource: "@LzyDoctrineBundle/Resources/config/routing.yml"
    prefix:   /

lzy_controller:
    resource: "@LzyControllerBundle/Resources/config/routing.yml"
    prefix:   /controller

lzy_console:
    resource: "@LzyConsoleBundle/Resources/config/routing.yml"
    prefix:   /

lzy_bundle:
    resource: "@LzyBundleBundle/Resources/config/routing.yml"
    prefix:   /bundle

lzy_assetic:
    resource: "@LzyAsseticBundle/Resources/config/routing.yml"
    prefix:   /assetic

