lzy_routing:
    resource: "@LzyRoutingBundle/Resources/config/routing.yml"
    prefix:   /routing

lzy_logger:
    resource: "@LzyLoggerBundle/Resources/config/routing.yml"
    prefix:   /logger

lzy_form:
    resource: "@LzyFormBundle/Resources/config/routing.yml"
    prefix:   /form

lzy_event:
    resource: "@LzyEventBundle/Resources/config/routing.yml"
    prefix:   /

lzy_doctrine:
    resource: "@LzyDoctrineBundle/Resources/config/routing.yml"
    prefix:   /

lzy_controller:
    resource: "@LzyControllerBundle/Resources/config/routing.yml"
    prefix:   /controller

lzy_console:
    resource: "@LzyConsoleBundle/Resources/config/routing.yml"
    prefix:   /

lzy_bundle:
    resource: "@LzyBundleBundle/Resources/config/routing.yml"
    prefix:   /bundle

lzy_assetic:
    resource: "@LzyAsseticBundle/Resources/config/routing.yml"
    prefix:   /assetic

