security:
  encoders:
    Lzy\SecurityAuthenticationBundle\Entity\User:
        algorithm: bcrypt
  providers:
    lzy_db_provider:
      entity:
        class: LzySecurityAuthenticationBundle:User
  firewalls:
    main:
      anonymous: ~
    #   provider: lzy_db_provider
    #   form_login:
    #     login_path: /security/login
    #     check_path: /security/login_check
