lzy_blog_posts:
    path:     /posts/{page}
    defaults: { _controller: LzyBlogBundle:Frontend:index, page: 1 }

lzy_blog_post:
    path:     /post/{id}
    defaults: { _controller: LzyBlogBundle:Frontend:post }

lzy_blog_homepage:
    path:     /
    defaults: { _controller: LzyBlogBundle:Frontend:index }
