# parameters:
#   blog.general.em: "@doctrine.orm.entity_manager"

services:
  blog.data:
    class: Lzy\BlogBundle\Service\Data
    arguments: ["@doctrine.orm.entity_manager"]
  # blog.posts:
  #   class: Lzy\BlogBundle\Service\Post
  #   arguments: ["@doctrine.orm.entity_manager"]
  blog.options:
    class: Lzy\BlogBundle\Service\Options
    arguments: ["@doctrine.orm.entity_manager"]