lzy_routing_homepage:
    path:     /
    defaults: { _controller: LzyRoutingBundle:Default:index }

lzy_routing_https:
    path:     /https
    defaults: { _controller: LzyRoutingBundle:Default:https }
    schemes: [https]
