lzy_routing_homepage:
  path: /
  defaults: { _controller: LzyRoutingBundle:Default:index }

lzy_routing_https:
  path: /https
  defaults: { _controller: LzyRoutingBundle:Default:https }
  schemes: [https]

lzy_routing_redirect:
  path: /redirect
  defaults:
    _controller: FrameworkBundle:Redirect:redirect
    route: lzy_routing_homepage
    permanent: true

lzy_routing_get:
  path: /get
  defaults: { _controller: LzyRoutingBundle:Default:get }
  methods: [GET]

lzy_routing_put:
  path: /put
  defaults: { _controller: LzyRoutingBundle:Default:put }
  methods: [PUT]

lzy_routing_delete:
  path: /delete
  defaults: { _controller: LzyRoutingBundle:Default:delete }
  methods: [DELETE]

lzy_routing_param:
  path: /{_prefix}/param
  defaults: { _controller: LzyRoutingBundle:Default:param }
  requirements:
    _prefix: '%lzy_routing_prefix%'

lzy_routing_pass_info:
  path: /extra/{param}
  defaults:
    _controller: LzyRoutingBundle:Default:passInfo
    param: 1
    title: "Hello world"
