<?php

namespace Lzy\SecurityAuthenticationBundle\Entity;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
use Doctrine\ORM\EntityRepository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

  /**
   * 
   * @param string $username
   * @return \Lzy\SecurityAuthenticationBundle\Entity\User
   * @throws \Symfony\Component\Security\Core\Exception\UsernameNotFoundException
   */
  public function loadUserByUsername($username) {
    $user = $this->createQueryBuilder('u')
      ->where('u.username = :username OR u.email = :email')
      ->setParameter('username', $username)
      ->setParameter('email', $username)
      ->getQuery()
      ->getOneOrNullResult();

    if (null === $user) {
      $message = sprintf(
        'Unable to find an active admin LzySecurityAuthenticationBundle:User object identified by "%s".', $username
      );
      throw new UsernameNotFoundException($message);
    }

    return $user;
  }

}
