doctrine:
    resource: "@ValidationDummyBundle/Resources/config/routing.yml"
    prefix:   /validation

doctrine:
    resource: "@DoctrineDummyBundle/Resources/config/routing.yml"
    prefix:   /doctrine

new:
    resource: "@NewBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

routing_hello:
    path: /routing
    defaults: { _controller: AppBundle:Routing:index }

routing_param:
    path: /routing/param/{page}
    defaults: { _controller: AppBundle:Routing:param, page: 1 }

routing_get:
    path: /routing/get
    defaults: { _controller: AppBundle:Routing:get }
    methods: [GET]

routing_url:
    path: /routing/url
    defaults: { _controller: AppBundle:Routing:url }
