CREATE TABLE product ( id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, price NUMERIC(10, 2) NOT NULL, description LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER
SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

