services:
  lzy.is:
    class: Lzy\CmsBundle\Service\Is
    arguments: []
  entity.factory:
    class: Lzy\CmsBundle\Service\EntityFactory
    arguments: []
    calls:
      - ['setIs', ['@lzy.is']]
      - ['setSlugify', ['@slugify']]
  page.factory:
    class: Lzy\CmsBundle\Service\PageFactory
    arguments: []
    calls:
      - ['setIs', ['@lzy.is']]