services:
  lzy.is:
    class: Lzy\CmsBundle\Service\Is
    arguments: []
  cms.entity.factory:
    class: Lzy\CmsBundle\Service\EntityFactory
    arguments: []
    calls:
      - ['setIs', ['@lzy.is']]
      - ['setSlugify', ['@slugify']]
  cms.entity.manager:
    class: Lzy\CmsBundle\Manager\EntityManager
    arguments: []
    calls:
      - ['setEntitiyManager', ['@doctrine.orm.entity_manager']]
      - ['setFactory', ['@cms.entity.factory']]
      - ['setIs', ['@lzy.is']]
  cms.page.factory:
    class: Lzy\CmsBundle\Service\PageFactory
    arguments: []
    calls:
      - ['setIs', ['@lzy.is']]