create:
    path: /create
    defaults: { _controller: DoctrineDummyBundle:Basic:create }

view:
    path: /view/{id}
    defaults: { _controller: DoctrineDummyBundle:Basic:view }

update:
    path: /update/{id}/{name}
    defaults: { _controller: DoctrineDummyBundle:Basic:update }