create:
    path: /create
    defaults: { _controller: DoctrineDummyBundle:Basic:create }

view:
    path: /view/{id}
    defaults: { _controller: DoctrineDummyBundle:Basic:view }

update:
    path: /update/{id}/{name}
    defaults: { _controller: DoctrineDummyBundle:Basic:update }

delete:
    path: /delete/{id}
    defaults: { _controller: DoctrineDummyBundle:Basic:delete }

dql:
    path: /query/dql/{price}
    defaults: { _controller: DoctrineDummyBundle:Query:dql }

builder:
    path: /query/builder/{price}
    defaults: { _controller: DoctrineDummyBundle:Query:builder }

custom_repository:
    path: /query/builder/all
    defaults: { _controller: DoctrineDummyBundle:Query:custom }

association_create:
    path: /association/create
    defaults: { _controller: DoctrineDummyBundle:Association:create }