lzy_templating_homepage:
    path:     /
    defaults: { _controller: LzyTemplatingBundle:Default:index }

lzy_templating_extension:
    path:     /extension
    defaults: { _controller: LzyTemplatingBundle:Default:extension }
