lzy_security_login:
  path: /login
  defaults: { _controller: LzySecurityAuthenticationBundle:Security:login }

lzy_security_login_check:
  path: /login_check
  defaults: { _controller: LzySecurityAuthenticationBundle:Security:loginCheck }