lzy_assetic_homepage:
    path:     /
    defaults: { _controller: LzyAsseticBundle:Default:index }

lzy_assetic_including_js:
    path:     /including_js_css_img
    defaults: { _controller: LzyAsseticBundle:Default:includingJsCssImg }
