CREATE TABLE category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER
SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;


ALTER TABLE product ADD category_id INT DEFAULT NULL;


ALTER TABLE product ADD CONSTRAINT FK_D34A04AD12469DE2
FOREIGN KEY (category_id) REFERENCES category (id);


CREATE INDEX IDX_D34A04AD12469DE2 ON product (category_id);

