services:
    monolog.processor.session_request:
        class: Lzy\LoggerBundle\SessionRequestProcessor
        arguments:  ["@session"]
        tags:
            - { name: monolog.processor, method: processRecord }