new:
    path:     /new
    defaults: { _controller: FormDummyBundle:Default:new }

handle:
    path:     /handle
    defaults: { _controller: FormDummyBundle:Default:handle }

multiple:
    path:     /multiple
    defaults: { _controller: FormDummyBundle:Default:multiple }
